[package]
name = "turbo-clicker"
version = "0.0.6"
authors = ["Heathcliff <heathcliff@heathcliff.eu>"]
edition = "2024"
description = "GUI based auto-clicker for Linux. It uses uinput and should thus work independently of wayland or x11."
readme = "README.md"
repository = "https://github.com/heathcliff26/turbo-clicker"
license = "Apache-2.0"
exclude = [
    ".github",
    ".vscode",
    "hack",
    ".editorconfig",
    ".sourcery.yaml",
    "Makefile",
]

[dependencies]
evdev = "0.13.2"
libc = "0.2.177"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
slint = { version = "1.14.1", default-features = false, features = [
    "std",
    "accessibility",
    "compat-1-2",
    "backend-qt",
] }

[build-dependencies]
slint-build = "1.14.1"

[dev-dependencies]
i-slint-backend-testing = "=1.14.1"
serial_test = "3.2.0"

[profile.release]
strip = "symbols"
lto = true
codegen-units = 1
